import React from 'react';

const Lorem = <article>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At urna condimentum mattis pellentesque id nibh tortor id. Egestas dui id ornare arcu odio ut. Blandit turpis cursus in hac habitasse platea. Non diam phasellus vestibulum lorem sed risus ultricies. Auctor eu augue ut lectus arcu. Malesuada pellentesque elit eget gravida. Scelerisque varius morbi enim nunc faucibus a pellentesque. Est pellentesque elit ullamcorper dignissim cras tincidunt. Vel pharetra vel turpis nunc. Quis varius quam quisque id diam vel. Commodo odio aenean sed adipiscing. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Id aliquet risus feugiat in. Duis convallis convallis tellus id interdum. Ut aliquam purus sit amet luctus venenatis lectus magna.
  </p>
  <p>Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Sit amet mauris commodo quis imperdiet. Nulla pellentesque dignissim enim sit amet venenatis urna. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Aenean pharetra magna ac placerat. Pulvinar etiam non quam lacus. Commodo elit at imperdiet dui accumsan sit. Auctor urna nunc id cursus metus aliquam eleifend. Etiam dignissim diam quis enim. Risus ultricies tristique nulla aliquet enim tortor. Posuere ac ut consequat semper viverra nam. Nam libero justo laoreet sit amet cursus. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Lectus arcu bibendum at varius vel. Magna fringilla urna porttitor rhoncus dolor.</p>
  <p>Enim sit amet venenatis urna cursus eget nunc. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Maecenas accumsan lacus vel facilisis volutpat est. Suscipit tellus mauris a diam maecenas sed enim ut sem. Habitasse platea dictumst quisque sagittis purus sit. In nisl nisi scelerisque eu. Sit amet cursus sit amet dictum sit amet justo. A iaculis at erat pellentesque adipiscing commodo elit. Justo laoreet sit amet cursus. Platea dictumst vestibulum rhoncus est. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Viverra orci sagittis eu volutpat odio. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Quam id leo in vitae turpis massa sed.

Convallis convallis tellus id interdum velit laoreet. Elementum sagittis vitae et leo duis ut. Nisi scelerisque eu ultrices vitae. Mattis aliquam faucibus purus in massa. Id eu nisl nunc mi ipsum faucibus vitae. Libero justo laoreet sit amet. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Ipsum dolor sit amet consectetur adipiscing elit. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Posuere morbi leo urna molestie at. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Eleifend quam adipiscing vitae proin sagittis nisl. Euismod elementum nisi quis eleifend quam. Massa ultricies mi quis hendrerit dolor magna eget. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Mauris a diam maecenas sed enim. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim diam vulputate ut pharetra sit amet aliquam id diam.</p>
</article>;

export default Lorem;


